### ISSUE TITLE
GPL vs. LGPL

### ISSUE THREAD

**Issue by miho** [RobertBColton/DockFX#1]
The README file gives the impression that the library is released under pure GPL license whereas the LICENSE file contains the LGPL license. I think you should update the README file and cite the LGPL license there as well to prevent confusion.

**Comment by RobertBColton** [comment]
Thank you for your input! I will consider relicensing the library as I do want it to be used in proprietary applications. I am not too familiar with licensing so I will need to speak with a colleague of mine first to advise me. I understand the concerns and I will resolve this. I am also interested in getting this into the ControlsFX library.

**Comment by zmb3** [comment]
Great library!  This definitely does fill a void.  I was looking for something like this recently and didn't find much.

I don't think he's asking you to re-license it though.  You have already released the code with a LICENSE file that contains the LGPL.  Was this your intent or was this a mistake?  It's not clear based on the README file and your comment above.

**Comment by RobertBColton** [comment]
That was a mistake the GPLv3 was my intent, GitHub auto-generated the LICENSE file and did not distinguish that it was the LGPL, please disregard it for now. However, I will likely be licensing it under the LGPL as well and thus why I have not removed the license yet. I just need to double check a few provisions with a colleague of mine and if everything is ok I will probably do it later tonight. Thank you for your interest and your patience.

**Comment by RobertBColton** [comment]
@zmb3 @miho The license has been changed to the LGPL v3. Please feel free to use the library in proprietary applications, but do consider sending patches upstream so that we may fix them for all users of the library. Thank you.

**Comment by RobertBColton** [comment]
Small update in that the project has changed in b5e4f36594c02e2b3eba0162d267dd2fe5efdba5 to the permissive MPLv2 license. I hope that this will make the library friendly to use in proprietary applications while encouraging shared contributions for the academic aspects of the project. 👍
