### ISSUE TITLE
An option to dock as a tab on an existing panel

### ISSUE THREAD

**Issue by clumsy** [RobertBColton/DockFX#16]
This is similar to what other docking managers (like https://www.syncfusion.com/products/wpf/docking-manager) are providing.
This could be an optional functionality, but there's room for it in the existing control - the middle button.

**Comment by jasons2000** [comment]
agreed, I think this should be optional.

**Comment by jasons2000** [comment]
Is this not the same as?
https://github.com/RobertBColton/DockFX/issues/14

**Comment by RobertBColton** [comment]
This feature is separate from #14, and is planned for a future release. Please see #10.

**Comment by clumsy** [comment]
I agree, it's a dupe.

**Comment by RobertBColton** [comment]
I've scoped the original ticket to cover both aspects.
