### ISSUE TITLE
dock-root-pane in DockPane.java becomes dark instead of transparent while dragging.

### ISSUE THREAD

**Issue by kuldeep9922** [RobertBColton/DockFX#19]
Hi, 

While dragging one node the entire dockpane gets black layout with position indicators only. I want it to be transparent as it is in the demo. Please see the image to get a better idea.
![429e4786-1860-11e6-8e4a-f88857be5f73](https://cloud.githubusercontent.com/assets/15650037/15213083/8f3908cc-1862-11e6-9a56-cc104c167e42.png)

Here in this image, I want the background of position indicators to be transparent and expose the internal components. I tried using "-fx-background-color: transparent" in dock-root-pane css class.

Please suggest, what can be done about it?

**Comment by RobertBColton** [comment]
I am having a hard time understanding what exactly the issue is with this one. I would need to see a reproducible test case that shows the issue.

I think you are asking to set the background of the docking buttons transparent and only show the icon. So I think you want this at the end of your stylesheet:
```css
.dock-pos-indicator .button {
  -fx-background-color: transparent;
}
.dock-root-pane .button {
  -fx-background-color: transparent;
}
```

**Comment by kuldeep9922** [comment]
Hi, 
I'm sorry if you didn't get it previously. The solution you suggest is for buttons but for me buttons are fine and I don't want to change that. My problem is the large black background of position indicators, i.e. position area indicator is black. I've highlighted the black area I'm talking about in attached photo.

![429e4786-1860-11e6-8e4a-f88857be5f73](https://cloud.githubusercontent.com/assets/15650037/15282567/cb67a13a-1b61-11e6-9ed0-38aa373a98a2.png)

I hope its clear now, I wanna see components beneath it, instead of black window. For example, in your demo file,  position area indicator is transparent and while dragging, I can see the components at back. However, I can't see the same in mine. It's hidden by black area indicator.

Let me know, if its still unclear.

**Comment by RobertBColton** [comment]
Alright that helps. Can you show me how exactly you are setting those areas to be black? Or just show me your whole stylesheet.

**Comment by kuldeep9922** [comment]
No, I'm not setting it black. Still, I'm pasting my complete css.

`
/**
* @file Default.css
* @brief Default styling for docking controls.
*
* @section License
*
* Copyright (C) 2015 Robert B. Colton
* This file is a part of the DockFX Library.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of thDockTitleBare GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
**/

/*******************************************************************************
 *                                                                             *
 * DockPane                                                                    *
 *                                                                             *
 ******************************************************************************/
.color-palette {
    -fx-background-radius: 0, 0;
    -fx-effect: null;
}

/* .dock-area-indicator {
  -fx-fill: -fx-selection-bar;
  -fx-opacity: 0.5;
  -fx-stroke: rgba(50, 50, 100, 0.4);
  -fx-stroke-width: 6;
  -fx-stroke-type: inside;
  -fx-stroke-dash-array: 8 4;
  -fx-stroke-line-cap: butt;
} */

.dock-pos-indicator {
  -fx-padding: 10;
  -fx-hgap: 30;
  -fx-vgap: 30;
  -fx-shape: "M0,10 a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0";
  -fx-background-color: rgba(50, 50, 100, 0.4);
  -fx-border-width: 50;
  -fx-border-color: rgba(50, 50, 100, 0.2);
}

/* JavaFX developers really seem to have fat fingers? */
.dock-pos-indicator .button {
  -fx-padding: 4;
}

/* This stops the stack pane containing the aligned
 * root dock position indicators from offsetting
 * them when one of them is set to the hover style.
 * It gives them just enough room to breathe from the border.
 */
 
.dock-root-pane {
  -fx-padding: 5;
  -fx-background-color: transparent;
}

/* JavaFX developers really seem to have fat fingers? */
.dock-root-pane .button {
  -fx-padding: 4;
}

/* Set the icons for the indicator buttons here. */
.dock-center {
  -fx-graphic: url(center.png);
}

.dock-top {
  -fx-graphic: url(top.png);
}

.dock-right {
  -fx-graphic: url(right.png);
}

.dock-bottom {
  -fx-graphic: url(bottom.png);
}

.dock-left {
  -fx-graphic: url(left.png);
}

.dock-top-root {
  -fx-graphic: url(top.png);
}

.dock-right-root {
  -fx-graphic: url(right.png);
}

.dock-bottom-root {
  -fx-graphic: url(bottom.png);
}

.dock-left-root {
  -fx-graphic: url(left.png);
}

/*******************************************************************************
 *                                                                             *
 * DockNode                                                                    *
 *                                                                             *
 ******************************************************************************/

.dock-node-border {
  -fx-padding: 5;
  -fx-background-radius: 5;
  -fx-effect: dropshadow( three-pass-box, rgba(0,0,0,0.4), 10,0.2,0,0 );
}

.dock-node-border:maximized {
  -fx-padding: 0;
}

/* It is necessary that dock node's have a background color
 * because some panes used as content such as TabPane with empty
 * tabs will be fully transparent.
 */
.dock-node {
  -fx-background-color: -fx-background;
}

.dock-title-bar {
  -fx-background-color: -fx-background;
  -fx-padding: 2;
  -fx-spacing: 3;
  -fx-border-width: 1;
  -fx-border-color: -fx-outer-border;
}

.dock-title-label {
  -fx-graphic: url(docknode.png);
  -fx-padding: 0 0 3 0;
  -fx-text-fill: white;
  -fx-effect: dropshadow( gaussian, rgba(255,255,255,0.2), 0,0,0,1 );
}

/* We want small buttons for our dock's title bar
 * but we have to make sure that the top and bottom
 * are a good ratio of the left and right padding.
 * If not we get extra padding on the bottom when the
 * button is hovered, some factor of the default style's
 * excessively wide buttons.
 */
.dock-title-bar .button {
  -fx-padding: 1 4 1 4;
}

.dock-add-ticker-button {
	-fx-graphic: url(plus.png);
  	-fx-background-color: transparent;
  	-fx-focus-color: transparent;
}

#add-ticker-button:focused {
	-fx-graphic: url(plus.png);
  	-fx-background-color: transparent;
  	-fx-focus-color: transparent;
}

/* Set the icons for the dock title bar's buttons here. */
.dock-state-button {
  -fx-graphic: url(restore.png);
  -fx-background-color: transparent;
}

.dock-node:floating .dock-state-button {
  -fx-graphic: url(restore.png);
  -fx-background-color: transparent;
}

.dock-node:maximized .dock-state-button {
  -fx-graphic: url(maximize.png);
  -fx-background-color: transparent;
}

.dock-close-button {
  -fx-graphic: url(close.png);
  -fx-background-color: transparent;
}`

**Comment by RobertBColton** [comment]
I am not seeing what you are seeing. I pasted your css into the demo and for me it is still transparent:

![DockFX Transparent Hover](https://cloud.githubusercontent.com/assets/3212801/15286881/5c4cd5ec-1b2d-11e6-9ffa-57fc64255447.png)

**Comment by kuldeep9922** [comment]
I've edited my last comment. By mistake I missed some part of my css. I've edited and pasted the complete css code. I've observed new something, please see my edited last comment and try again if its still not reproducible.

**Comment by RobertBColton** [comment]
The culprit appears to be the following code:
```css
/* .dock-area-indicator {
  -fx-fill: -fx-selection-bar;
  -fx-opacity: 0.5;
  -fx-stroke: rgba(50, 50, 100, 0.4);
  -fx-stroke-width: 6;
  -fx-stroke-type: inside;
  -fx-stroke-dash-array: 8 4;
  -fx-stroke-line-cap: butt;
} */
```

**Comment by kuldeep9922** [comment]
No, I already tried it. This code is not creating any problem :(

**Comment by RobertBColton** [comment]
Oh no, I was saying I only see the problem when it is commented. When it is uncommented I do not see the problem.

**Comment by kuldeep9922** [comment]
It's not working even after uncommenting :(

**Comment by RobertBColton** [comment]
When I uncomment that code it looks exactly like the screenshot I posted just a little bit ago. :/

**Comment by kuldeep9922** [comment]
Yes, I understood your approach perfectly. I need to play around with this to make it work. Thanks :)

**Comment by RobertBColton** [comment]
Alright, I am not really sure what else could be the problem. If you have any other issues let me know!

**Comment by kuldeep9922** [comment]
Finally, I found out that "root" class in stylesheet was creating problem, I removed this root class and everything worked well as expected. Btw thanks for the time.

**Comment by RobertBColton** [comment]
No problem I am glad you got it solved, I am sorry I didn't manage to figure it out for you!
