### ISSUE TITLE
Provide side frame ordering

### ISSUE THREAD

**Issue by dprutean** [RobertBColton/DockFX#28]
As I can see now the frames can be placed North, South, East, West. In many situations I have to place frames one under the other, or on the same position. Having indexes and sub-indexes for each frame would help to position them. Check the jide docking.

![image](https://cloud.githubusercontent.com/assets/4970910/21449312/502cca34-c8ec-11e6-8c96-b2ac7cb0cd7f.png)

**Comment by RobertBColton** [comment]
This is actually supported but I don't demonstrate it in the demo. There is an overload for dock that takes a sibling: https://github.com/RobertBColton/DockFX/blob/80c5e58344850b9ec92c84cb6fb9b56d6a1066f3/src/main/java/org/dockfx/DockNode.java#L626

I'll leave this open as a reminder to myself to add it into the demo so people can discover the feature easier.

**Comment by RobertBColton** [comment]
Forgive me if this is incorrect, and I will reopen this ticket, but I believe that #14 covers the same feature. So I am going to close this out as a duplicate. What was requested here is the ability to dock two nodes together into tabs and reorder them, which is essentially the feature #14 covers. Please follow that issue for further updates if it does get added. Thanks!
