### ISSUE TITLE
Needs to Support Java 9

### ISSUE THREAD

**Issue by jasons2000** [RobertBColton/DockFX#33]
Needs to Support Java 9

**Comment by jasons2000** [comment]
jdeps output

C:\Users\Jason\dev\DockFX\target>jdeps -jdkinternals classes
classes -> C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\jfxrt.jar
   org.dockfx.DockEvent (classes)
      -> com.sun.javafx.scene.input.InputEventUtils         JDK internal API (jfxrt.jar)
   org.dockfx.DockPane (classes)
      -> com.sun.javafx.css.StyleManager                    JDK internal API (jfxrt.jar)
   org.dockfx.DockTitleBar (classes)
      -> com.sun.javafx.stage.StageHelper                   JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin (classes)
      -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.control.behavior.TabPaneBehavior JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.control.skin.BehaviorSkinBase JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$StyleableProperties (classes)
      -> com.sun.javafx.css.converters.EnumConverter        JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$TabContentRegion (classes)
      -> com.sun.javafx.scene.traversal.Direction           JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.traversal.TraversalEngine     JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$TabHeaderSkin (classes)
      -> com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.control.skin.resources.ControlResources JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$TabHeaderSkin$2 (classes)
      -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.control.behavior.TabPaneBehavior JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$TabHeaderSkin$3 (classes)
      -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.control.behavior.TabPaneBehavior JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$TabHeaderSkin$4 (classes)
      -> com.sun.javafx.util.Utils                          JDK internal API (jfxrt.jar)
   org.dockfx.pane.skin.ContentTabPaneSkin$TabHeaderSkin$5 (classes)
      -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (jfxrt.jar)
      -> com.sun.javafx.scene.control.behavior.TabPaneBehavior JDK internal API (jfxrt.jar)

**Comment by RobertBColton** [comment]
Correct me if I'm wrong, but `jdk1.8.0_162` is not Java 9? There should be no problem here, these look like internal JavaFX issues with your Java setup. DockFX makes no use of internal APIs.

**Comment by jasons2000** [comment]
jdeps comes with jdk1.8, and can be used go identify internal dependencies. So currently DockFX does indeed not work with JDK 9 because of the use of these internals.

However, their is switch with JDK 9 that enables access to some of these internals. This helps but their are still some issues with some api changes of these internals.

I'm working through some of these on one of the forks  and should hopefully check in later today or tomorrow.

One concern is the removal of the StageHelper.getStages() method. This stackoverflow question details my concern.
https://stackoverflow.com/questions/47751399/get-all-stages-on-javafx-scene-graph

Lastly, the ability to call internals will be removed from Jdk 10, which is due next month, so we will need to migrate away from all use of internals.

**Comment by jasons2000** [comment]
Created a Java 9 compatible version at https://github.com/jasons2000/DockFX/ for the maven project

**Comment by jasons2000** [comment]
its on my branch

**Comment by RobertBColton** [comment]
I've submitted a workaround for now: https://github.com/RobertBColton/DockFX/commit/8d4413408217b21223e8ca9a90da9439ece60619

Java 9 release is available:
https://github.com/RobertBColton/DockFX/releases
