### ISSUE TITLE
Timing issue setting floating property on undock

### ISSUE THREAD

**Issue by stevel05** [RobertBColton/DockFX#35]
If I set a listener on the dockedProperty and undock a dock by dragging it, and in the listener test the floatingProperty it is still set to false.

This causes a problem as I want to know if the undocked dock is actually floating or closed (as in not floating and not docked.).

If I check the floatingProperty in a runLater sub it has correctly changed to true

**Comment by RobertBColton** [comment]
Hrm, this definitely seems undesirable as I was actually going to rely on what you described in order to update DockFX for Java 9. I don't see yet why this is delayed, because as soon as the drag is detected on the title bar the dock node is set to floating:
https://github.com/RobertBColton/DockFX/blob/8d4413408217b21223e8ca9a90da9439ece60619/src/main/java/org/dockfx/DockTitleBar.java#L314
Which causes the floating property to be set to true:
https://github.com/RobertBColton/DockFX/blob/8d4413408217b21223e8ca9a90da9439ece60619/src/main/java/org/dockfx/DockNode.java#L285

**Comment by stevel05** [comment]
Possibly because in Docknode you are undocking (setting the dockedProperty) at line 246 and not setting the floatingProperty until line 285.  Therefore the dockedProperty changelistener is being fired before the floating property is updated.

**Comment by RobertBColton** [comment]
Alright, I'll see if I can push a patch for it shortly without causing a regression.

**Comment by stevel05** [comment]
Thanks very much, and not a problem

**Comment by RobertBColton** [comment]
While I'm going to be addressing this, I want to perhaps look at this another way. I think it may be confusing that I have both `dockedProperty` and `floatingProperty` which for the most part have the same meaning. When a node is undocked, it's essentially floating, and when it's floating, it's obviously not docked. There is an inbetween state where it can be neither, but for the purposes of DockFX, it's not useful to define that.

So considering this, would you be alright with me combining the docked and floating properties together into one? I would deprecate one and continue use of the other. I think that would make the API less confusing as well as fix this issue too.

**Comment by stevel05** [comment]
The only problem I could see then is that it would not be possible to tell if the dockpane was not visible (Closed).

**Comment by stevel05** [comment]
OK, sounds good to me.

**Comment by RobertBColton** [comment]
Alright, I've patched the issue: e66e091ff4514602ee1396ab1178ee0a74bea11f

To avoid breaking any existing users over something trivial, I simply decided to go with the first fix you suggested, to set the floating property before undocking.

I've also generated a new beta release with the fix:
https://github.com/RobertBColton/DockFX/releases/tag/0.3b
