### ISSUE TITLE
add document docking

### ISSUE THREAD

**Issue by oxysoft** [RobertBColton/DockFX#4]
Is this planned already? Like docking documents to a dock node and it creates the tabs, you know it

otherwise, good job on DockFX, this is what was missing the most with JavaFX imo

**Comment by RobertBColton** [comment]
I think you mean docking to the center of another dock node? For instance, on the dock indicator popup there is the circle, there is actually supposed to be a button in the middle to stack them in tabs. If that's what you are referring then yes definitely, I just commented out the button for right now to add the support at a later time. I want to make the core docking framework as stable as possible first.

If that's not what you mean, please clarify. And thank you for your feedback!

**Comment by oxysoft** [comment]
Yes, exactly that!

Thanks
