### ISSUE TITLE
Is development still active?

### ISSUE THREAD

**Issue by oxysoft** [RobertBColton/DockFX#9]
There hasn't been any activity in the past 5 months which is unfortunate because this has a lot of potential. So has it been abandoned?

**Comment by jasons2000** [comment]
I contacted Robert about this. They are waiting until the following two JDK bugs (listed below) are resolved before they continue with more serious development.

https://bugs.openjdk.java.net/browse/JDK-8133335
https://bugs.openjdk.java.net/browse/JDK-8134278

I agree DockFX has great potential and its a shame that it seems development has currently been suspended. I'm still using DockFX, as is, in some of my products and I find it still works quite well despite the outstanding bugs.

**Comment by oxysoft** [comment]
Ah I see. Well then let's hope these fixes happen
